export const MapThemes = [
  {
    themeTitle: "City",
    themeLayers: [
      { title: "Park Outdoor Recreation Facilities", source: "Parks" },
      { title: "Park Playgrounds", source: "Parks" },
      { title: "Park Specimen Trees", source: "Parks" },
      { title: "Park Sports Fields", source: "Parks" },
      { title: "Trails and Paths", source: "Parks" },
      { title: "Road Surface", source: "Transportation" },
      { title: "Road Names", source: "Transportation" },
      { title: "Buildings", source: "Buildings" },
      { title: "Water Courses", source: "Drainage" },
      { title: "Lots", source: "Lots" },
      { title: "Addresses (black)", source: "Annotation_Dimensions" },
      { title: "Park Name Labels", source: "Parks" },
    ],
  },
  {
    themeTitle: "Infrastructure",
    themeLayers: [
      { title: "Park Outdoor Recreation Facilities", source: "Parks" },
      { title: "Park Playgrounds", source: "Parks" },
      { title: "Park Sports Fields", source: "Parks" },
      { title: "Trails and Paths", source: "Parks" },
      { title: "Road Surface", source: "Transportation" },
      { title: "Road Names", source: "Transportation" },
      { title: "Buildings", source: "Buildings" },
      { title: "Water Courses", source: "Drainage" },
      { title: "Lots", source: "Lots" },
      { title: "Addresses (black)", source: "Annotation_Dimensions" },
      { title: "Park Name Labels", source: "Parks" },
      { title: "Easements (black)", source: "Legal" },
      { title: "Rights of Way (black)", source: "Legal" },
      { title: "Drainage Mains", source: "Drainage" },
      { title: "Sanitary Mains", source: "Sanitary" },
      { title: "Water Mains", source: "Water" },
      { title: "Contours - 5 metre", source: "Elevation" },
      { title: "Transit Stops (All Stops)", source: "Transportation" },
      { title: "Drainage Catch Basins", source: "Drainage" },
      { title: "Drainage Laterals", source: "Drainage" },
      { title: "Drainage Manholes", source: "Drainage" },
      { title: "Drainage Service Connections", source: "Drainage" },
      { title: "Sanitary Laterals", source: "Sanitary" },
      { title: "Sanitary Manholes", source: "Sanitary" },
      { title: "District Energy Mains", source: "DistrictEnergy" },
      { title: "Water Service Connections", source: "Water" },
    ],
  },
  {
    themeTitle: "Property",
    themeLayers: [
      { title: "Park Outdoor Recreation Facilities", source: "Parks" },
      { title: "Park Playgrounds", source: "Parks" },
      { title: "Park Sports Fields", source: "Parks" },
      { title: "Trails and Paths", source: "Parks" },
      { title: "Road Surface", source: "Transportation" },
      { title: "Road Names", source: "Transportation" },
      { title: "Buildings", source: "Buildings" },
      { title: "Water Courses", source: "Drainage" },
      { title: "Lots", source: "Lots" },
      { title: "Addresses (black)", source: "Annotation_Dimensions" },
      { title: "Park Name Labels", source: "Parks" },
      { title: "", source: "" },
      { title: "Rosemary Heights West", source: "SecondaryPlans" },
      { title: "North Cloverdale West", source: "SecondaryPlans" },
      { title: "North Grandview Heights", source: "SecondaryPlans" },
      { title: "South Newton", source: "SecondaryPlans" },
      { title: "Douglas", source: "SecondaryPlans" },
      { title: "West Cloverdale North", source: "SecondaryPlans" },
      { title: "Secondary Plan Boundaries", source: "SecondaryPlans" },
      { title: "East Newton South", source: "SecondaryPlans" },
      { title: "West Newton/Highway 10", source: "SecondaryPlans" },
      { title: "East Panorama Ridge", source: "SecondaryPlans" },
      { title: "West Newton North", source: "SecondaryPlans" },
      { title: "South Westminster", source: "SecondaryPlans" },
      { title: "Morgan Heights", source: "SecondaryPlans" },
      { title: "Rosemary Heights Central", source: "SecondaryPlans" },
      { title: "East Newton North", source: "SecondaryPlans" },
      { title: "East Clayton", source: "SecondaryPlans" },
      { title: "East Newton Business Park", source: "SecondaryPlans" },
      { title: "East Clayton Extension North of 72 Ave", source: "SecondaryPlans" },
      { title: "North Cloverdale East", source: "SecondaryPlans" },
      { title: "West Newton South", source: "SecondaryPlans" },
      { title: "West Cloverdale South", source: "SecondaryPlans" },
      { title: "East Clayton Extension West of 188 St", source: "SecondaryPlans" },
      { title: "Redwood Heights", source: "SecondaryPlans" },
      { title: "Rosemary Heights Business Park", source: "SecondaryPlans" },
      { title: "Sunnyside Heights", source: "SecondaryPlans" },
      { title: "Land Use Contracts", source: "Planning" },
      { title: "Dev Apps - All", source: "Planning" },
      { title: "Zoning Boundaries", source: "Planning" },
    ],
  },
];

export default MapThemes;
