export const MapThemes = [
  {
    themeTitle: "City",
    themeLayers: [
      { title: "Park Outdoor Recreation Facilities", source: "Parks" },
      { title: "Park Playgrounds", source: "Parks" },
      { title: "Park Specimen Trees", source: "Parks" },
      { title: "Park Sports Fields", source: "Parks" },
      { title: "Trails and Paths", source: "Transportation" },
      { title: "Road Surface", source: "Transportation" },
      { title: "Road Names", source: "Transportation" },
      { title: "Buildings", source: "Buildings" },
      { title: "Water Courses Internal", source: "Drainage_Secured" },
      { title: "Early Copy Lots", source: "Legal_Secured" },
      { title: "Lots", source: "Lots" },
      { title: "Addresses (black)", source: "Annotation_Dimensions" },
      { title: "Park title Labels", source: "Parks" },
    ],
  },
  {
    themeTitle: "Infrastructure",
    themeLayers: [
      { title: "Park Outdoor Recreation Facilities", source: "Parks" },
      { title: "Park Playgrounds", source: "Parks" },
      { title: "Park Specimen Trees", source: "Parks" },
      { title: "Park Sports Fields", source: "Parks" },
      { title: "Trails and Paths", source: "Transportation" },
      { title: "Road Surface", source: "Transportation" },
      { title: "Road Names", source: "Transportation" },
      { title: "Buildings", source: "Buildings" },
      { title: "Water Courses Internal", source: "Drainage_Secured" },
      { title: "Early Copy Lots", source: "Legal_Secured" },
      { title: "Lots", source: "Lots" },
      { title: "Addresses (black)", source: "Annotation_Dimensions" },
      { title: "Park Name Labels", source: "Parks" },
      { title: "", source: "" },
      { title: "Utility Main Offsets", source: "Annotation_Dimensions" },
      { title: "Easements (black)", source: "Legal" },
      { title: "Rights of Way (black)", source: "Legal" },
      { title: "Drainage Mains Internal", source: "Drainage_Secured" },
      { title: "Sanitary Mains Internal", source: "Sanitary_Secured" },
      { title: "Water Mains Internal", source: "Water_Secured" },
      { title: "Contours - 5 metre", source: "Elevation" },
      { title: "Transit Stops Internal (Accessible)", source: "Transportation_Secured" },
      { title: "Transit Stops Internal (Non-Accessible)", source: "Transportation_Secured" },
      { title: "Transit Stops Internal (Other)", source: "Transportation_Secured" },
      { title: "Drainage Catch Basins", source: "Drainage" },
      { title: "Drainage Devices", source: "Drainage" },
      { title: "Drainage Driveway Culverts", source: "Drainage_Secured" },
      { title: "Drainage Laterals Internal", source: "Drainage_Secured" },
      { title: "Drainage Manholes Internal", source: "Drainage_Secured" },
      { title: "Drainage Service Connections", source: "Drainage" },
      { title: "Sanitary Chambers", source: "Sanitary" },
      { title: "Sanitary Laterals Internal", source: "Sanitary_Secured" },
      { title: "Sanitary Manholes Internal", source: "Sanitary_Secured" },
      { title: "Water Service Connections Internal", source: "Water_Secured" },
      { title: "Archaeologically Sensitive Areas", source: "Environmental_Secured" },
      { title: "Trans Mountain Pipeline", source: "Infrastructure_Secured" },
      { title: "Trans Mountain Pipeline Buffer", source: "Infrastructure_Secured" },
    ],
  },
  {
    themeTitle: "Property",
    themeLayers: [
      { title: "Park Outdoor Recreation Facilities", source: "Parks" },
      { title: "Park Playgrounds", source: "Parks" },
      { title: "Park Specimen Trees", source: "Parks" },
      { title: "Park Sports Fields", source: "Parks" },
      { title: "Trails and Paths", source: "Transportation" },
      { title: "Road Surface", source: "Transportation" },
      { title: "Road Names", source: "Transportation" },
      { title: "Buildings", source: "Buildings" },
      { title: "Water Courses Internal", source: "Drainage_Secured" },
      { title: "Early Copy Lots", source: "Legal_Secured" },
      { title: "Lots", source: "Lots" },
      { title: "Addresses (black)", source: "Annotation_Dimensions" },
      { title: "Park Name Labels", source: "Parks" },
      { title: "", source: "" },
      { title: "Rosemary Heights West", source: "Planning" },
      { title: "North Cloverdale West", source: "Planning" },
      { title: "North Grandview Heights", source: "Planning" },
      { title: "South Newton", source: "Planning" },
      { title: "Douglas", source: "Planning" },
      { title: "West Cloverdale North", source: "Planning" },
      { title: "Secondary Plan Boundaries", source: "Planning" },
      { title: "East Newton South", source: "Planning" },
      { title: "West Newton/Highway 10", source: "Planning" },
      { title: "East Panorama Ridge", source: "Planning" },
      { title: "West Newton North", source: "Planning" },
      { title: "South Westminster", source: "Planning" },
      { title: "Morgan Heights", source: "Planning" },
      { title: "Rosemary Heights Central", source: "Planning" },
      { title: "East Newton North", source: "Planning" },
      { title: "East Clayton", source: "Planning" },
      { title: "East Newton Business Park", source: "Planning" },
      { title: "East Clayton Extension North of 72 Ave", source: "Planning" },
      { title: "North Cloverdale East", source: "Planning" },
      { title: "West Newton South", source: "Planning" },
      { title: "West Cloverdale South", source: "Planning" },
      { title: "East Clayton Extension West of 188 St", source: "Planning" },
      { title: "Rosemary Heights Business Park", source: "Planning" },
      { title: "Sunnyside Heights", source: "Planning" },
      { title: "Land Use Contracts", source: "Planning" },
      { title: "Dev Apps - All", source: "Planning" },
      { title: "Zoning Boundaries", source: "Planning" },
    ],
  },
];

export default MapThemes;
