import Extent from "@arcgis/core/geometry/Extent";
const settings = {
  userBase: "External",
  codeBase: "PROD",
  appName: "COSMOS",
  version: "4.5.1",
  serverName: "cosmos.surrey.ca",
  geometryServerurl: "https://gisservices.surrey.ca/arcgis/rest/services/Utilities/Geometry/GeometryServer",
  currentYearAerialLayerName: "Aerial Photo April 2021",
  aerialStreetViewTools: "Aerial,StreetView,Pictomerty",
  pictometryToolurl: "https://cosmos.surrey.ca/external/Pictometry/PictoViewer.aspx?",
  streetViewImageurl: {
    url: "https://maps.googleapis.com/maps/api/js?",
    key: "&key=AIzaSyDxqfLipfOy0NP3-j9PzytCtZ5-F4_cA0E",
  },
  lotOutlineLayerName: "Lots (Outline)",
  lotYellowLayerName: "Lots (Yellow)",
  lotOnAeriaLayerName: "Lot Ownership on Aerial",
  addressBlack: "Addresses (black)",
  addressYellow: "Addresses (yellow)",
  building: "Buildings",
  roadSurface: "Road Surface",
  specimenTrees: "Park Specimen Trees",
  trafficCamerasLayerName: "Traffic Cameras",
  trafficCameraImageField: "IMAGE",
  trafficCameraNameField: "CAMERA_NAME",
  fishClassificationFolder: "Land Use / Environment",
  identifyFieldAlias: "LOT ID",
  identifyField: "MSLINK",
  identifyFieldAliasWR: "Legal ID",
  identifyFieldWR: "Legal_Id",
  addressListMaxNumber: "50",
  whiteRockurl: "https://cosmos.surrey.ca/external/WROMS/",
  whiteRockBoundary: "511294.066,5427706.736,516141.034,5430935.986",
  surreyBoundary: "504000, 5425000, 524000, 5455000",
  surreyBoundaryLatLon: "-123.4789, 48.627, -122.004, 49.496,",
  dataServiceurl: "https://cosmos.surrey.ca/external/COSMOSWebServices/cosmos.svc/",
  noIdentifyLayerNames: ["Road Names", "Building Shadow", "Aerial Photo", "(labels)", "Intersection Search", "Address Search", "Road Surface"],
  startingExtent: new Extent({
    xmin: 505e3,
    ymin: 5425e3,
    xmax: 524e3,
    ymax: 5455e3,
    spatialReference: { wkid: 26910 },
  }),
  mapServices: [
    {
      id: "BaseMap",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Base_Map/MapServer/",
      type: "Dynamic",
      baseMapService: true,
    },
    {
      id: "Drainage",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Drainage/MapServer/",
      LegendHideLayers: "",
      type: "Dynamic",
    },
  ],
};

export default settings;
