const settings = {
  userBase: "External",
  codeBase: "PROD",
  appName: "COSMOS",
  version: "4.5.1",
  serverName: "cosmos.surrey.ca",
  geometryServerurl: "https://gisservices.surrey.ca/arcgis/rest/services/Utilities/Geometry/GeometryServer",
  currentYearAerialLayerName: "Aerial Photo April 2021",
  aerialStreetViewTools: "Aerial,StreetView,Pictomerty",
  pictometryToolurl: "https://cosmos.surrey.ca/external/Pictometry/PictoViewer.aspx?",
  streetViewImageurl: {
    url: "https://maps.googleapis.com/maps/api/js?",
    key: "&key=AIzaSyDxqfLipfOy0NP3-j9PzytCtZ5-F4_cA0E",
  },
  lotOutlineLayerName: "Lots (Outline)",
  lotYellowLayerName: "Lots (Yellow)",
  lotOnAeriaLayerName: "Lot Ownership on Aerial",
  addressBlack: "Addresses (black)",
  addressYellow: "Addresses (yellow)",
  building: "Buildings",
  roadSurface: "Road Surface",
  specimenTrees: "Park Specimen Trees",
  trafficCamerasLayerName: "Traffic Cameras",
  trafficCameraImageField: "IMAGE",
  trafficCameraNameField: "CAMERA_NAME",
  fishClassificationFolder: "Land Use / Environment",
  identifyFieldAlias: "LOT ID",
  identifyField: "MSLINK",
  identifyFieldAliasWR: "Legal ID",
  identifyFieldWR: "Legal_Id",
  addressListMaxNumber: "50",
  whiteRockurl: "https://cosmos.surrey.ca/external/WROMS/",
  whiteRockBoundary: "511294.066,5427706.736,516141.034,5430935.986",
  surreyBoundary: "504000, 5425000, 524000, 5455000",
  surreyBoundaryLatLon: "-123.4789, 48.627, -122.004, 49.496,",
  dataServiceurl: "https://cosmos.surrey.ca/external/COSMOSWebServices/cosmos.svc/",
  noIdentifyLayerNames: [
    "Road Names",
    "Building Shadow",
    "Aerial Photo",
    "(labels)",
    "Intersection Search",
    "Address Search",
    "Road Surface",
  ],
  mapServices: [
    {
      id: "BaseMap",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Base_Map/MapServer/",
      type: "Dynamic",
      baseMapService: true,
    },
    {
      id: "AerialImages",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/AerialImages/MapServer/",
      type: "Dynamic",
      baseMapService: true,
    },
    {
      id: "Lots",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Lots/MapServer/",
      VisibleLayers: "",
      type: "Dynamic",
      baseMapService: true,
    },
    {
      id: "Buildings",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Buildings/MapServer/",
      LegendHideLayers: "Building Shadow",
      Type: "Dynamic",
    },
    {
      id: "SecondaryPlans",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/SecondaryPlans/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Planning",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Planning/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Elevation",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Elevation/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Miscellaneous",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Miscellaneous/MapServer/",
      VisibleLayers: "",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Legal",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Legal/MapServer/",
      LegendHideLayers: "Address Search",
      Type: "Dynamic",
    },
    {
      id: "Transportation",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Transportation/MapServer/",
      LegendHideLayers: "Road Names,Intersection Search",
      Type: "Dynamic",
    },
    {
      id: "Parks",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Parks/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Infrastructure",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Infrastructure/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Sanitary",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Sanitary/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Drainage",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Drainage/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Water",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Water/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "DistrictEnergy",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/DistrictEnergy/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Safety",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Public/Safety/MapServer/",
      LegendHideLayers: "",
      Type: "Dynamic",
    },
    {
      id: "Annotation_Dimensions",
      url: "https://gisservices.surrey.ca/arcgis/rest/services/Annotation_Dimensions/MapServer/",
      Type: "Dynamic",
    },
  ],
};

export default settings;
